[32mINFO    [0m root:__init__.py:27 功能的名称为：test_ryvue 功能的描述为：None
[1m[31mERROR   [0m root:test_ryvue.py:76 userManagement_084断言失败，用例数据为：{'userName': 'userManagement_084', 'nickName': '', 'password': '123456', 'status': '0', 'postIds': [], 'roleIds': []}期望数据为：{'msg': '操作失败', 'code': 500}服务器返回的期望数据：{"msg":"\n### Error updating database.  Cause: java.sql.SQLException: Field 'nick_name' doesn't have a default value\n### The error may exist in URL [jar:file:/ruoyi/app/ruoyi-admin.jar!/BOOT-INF/lib/ruoyi-system-3.8.7.jar!/mapper/system/SysUserMapper.xml]\n### The error may involve com.ruoyi.system.mapper.SysUserMapper.insertUser-Inline\n### The error occurred while setting parameters\n### SQL: insert into sys_user(                  user_name,                                     password,       status,       create_by,            create_time    )values(                  ?,                                     ?,       ?,       ?,            sysdate()    )\n### Cause: java.sql.SQLException: Field 'nick_name' doesn't have a default value\n; Field 'nick_name' doesn't have a default value; nested exception is java.sql.SQLException: Field 'nick_name' doesn't have a default value","code":500}
[1m[31mERROR   [0m root:__init__.py:33 断言失败